-- AlterTable
ALTER TABLE "File" ADD COLUMN     "name" TEXT NOT NULL DEFAULT 'Blub',
ADD COLUMN     "size" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "timeUploaded" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
